### ISSUE TITLE
Spielplan

### ISSUE THREAD

**Issue by Jules-sh** [NickRTR-Schule/Gehweg-Parcours#1]
Backlog Item:
Als Spieler möchte ich einen Gehweg mit 14x6 Platten sehen, um die Hundehaufen dann zu erraten

Tätigkeiten:
UI bauen
Spielplan erstellen

**Comment by Adrian-Cxll** [comment]
** 20.05 09.07
In der Gui gibt es folgende Probleme:

- Bei manchen Platten kommt erst nach mehreren Klicks eine Zahl oder der Hundehaufen.
- Der Hundehaufen ist falsch
- Img von Kacke wird nicht richtig angezeigt
- die letzten Buttons haben keine Reaktion mehr bei Anklicken


Screenshot:
https://imgur.com/a/xRIq7g7

**Comment by Adrian-Cxll** [comment]
** 21.05 09.40
Sobald man die Gui / das Programm starteen möchte:

Nullpointer Exception
--> Imgicon problem?

Screenshot Konsole:
https://imgur.com/a/RQ7gR7J

**Comment by Jules-sh** [comment]
Problem sollte mit neustem Commit behoben sein.
Bitte testen und rückmelden
Problem war vermutlich, dass das Image geladen, aber nie skaliert und vernünftig gesetzt wurde

**Comment by NickRTR** [comment]
Image funktioniert jetzt, wird jedoch auf eine Platte gedrückt, erscheinen drei Punkte neben dem Image, weil nicht genug Platz für die Zahl der umliegenden Hundehaufen ist.:

![image](https://user-images.githubusercontent.com/95316598/169687533-8fc5904c-9d2a-4a44-b49f-9484ba4568ea.png)

**Comment by Adrian-Cxll** [comment]
**22.05 14:00
Die Dargestellten Zahlen der umliegenden Hundehaufen stimmen nicht mit den umliegenden Hundehaufen überein.
Der Error (-1) Ensteht auch bei Feldern der zweiten Reihe [Siehe leere Felder]

(Zahlen werden nun Angezeigt)

![grafik](https://user-images.githubusercontent.com/103188006/169694643-0287466b-506d-4b84-b0f0-c2d959a928b0.png)

**Comment by NickRTR** [comment]
@Adrian-Cxll dieser Comment passt besser zu Issue https://github.com/NickRTR-Schule/Gehweg-Parcours/issues/5
