### ISSUE TITLE
Start Platte aufdecken

### ISSUE THREAD

**Issue by Jules-sh** [NickRTR-Schule/Gehweg-Parcours#11]
Backlog Item:
Als Spieler möchte ich direkt nach dem Spielstart eine erste Gehwegplatte ohne Hundehaufen aufgedeckt und mit der Anzahl der umgebenen Hundehaufen angezeigt sehen, um nicht gleich am Anfang auf einen Hundehaufen zu treten.

Tätigkeiten:
- Startplatte aufdecken, bevor die Hundehaufen verteilt werden
- Startplatte in Verteilung der Hundeplatten ausnehmen

**Comment by NickRTR** [comment]
1. Zufällige Platte auswählen
2. wenn Hundehaufen auf Platte neue Platte auswählen
3. sonst ausgewählte Platte aufdecken

**Comment by Jules-sh** [comment]
Wenn man ein Spiel startet werden immer 2 Platten aufgedeckt. Eine mit Zahl und eine komplett leere

**Comment by Jules-sh** [comment]
Neustart von Eclipse hat das Problem behoben xD
