### ISSUE TITLE
Festlegen der Anzahl der Hundehaufen

### ISSUE THREAD

**Issue by Jules-sh** [NickRTR-Schule/Gehweg-Parcours#15]
Backlog Item:
Als Spieler möchte ich vor einem Spiel die Anzahl der versteckten Hundehaufen festlegen können, um den Schwierigkeitsgrad zu ändern.

Tätigkeiten:
- Globale Variable Anzahl der Hundehaufen
- Anzahl bei Generierung beachten
- Änderung der Variable durch ein Textfeld

**Comment by NickRTR** [comment]
Dieses Element soll am rechten Fensterrand, über der Spielanleitung eingebaut werden.

**Comment by Jules-sh** [comment]
Alles vorbereitet, allerdings muss noch eine Überprüfung eingebaut werden, sodass man nicht mehr Hundehaufen als Platten festlegen kann -> würde eine Endlosschleife geben

**Comment by NickRTR** [comment]
Außerdem muss noch eine Überprüfung hinzugefügt werden, die Testet ob die Eingabe valide (also eine Zahl über 0) ist.
