### ISSUE TITLE
Spielanleitung

### ISSUE THREAD

**Issue by NickRTR** [NickRTR-Schule/Gehweg-Parcours#16]
Eine Spielanleitung rechts neben dem Spielfeld und unter den nicht gesetzten Vermutungen, die den simplen Spielprozess erklärt.

1. Platte aufdecken: Um eine Platte aufzudecken, klicken Sie mit einem Linksklick auf die Platte.
2. Vermutung setzen: Vermuten Sie einen Hundehaufen auf einer Platte, können Sie mit Rechtsklick eine Flagge setzen.
3. Vermutung zurücknehmen: Möchten Sie eine Vermutung zurücknehmen, drücken Sie erneut mit Rechtsklick auf die Platte.

**Comment by Jules-sh** [comment]
Dieser Issue deckt ebenfalls die Dokumentation und Spielanleitung im Wiki ab
