### ISSUE TITLE
Statistik

### ISSUE THREAD

**Issue by Adrian-Cxll** [NickRTR-Schule/Gehweg-Parcours#26]
Nach dem Gewinnen oder Verlieren Statistiken anzeigen wie:

- [ ] Durchschnittliche Denkzeit
- [ ] Anzahl Flaggen richtig gesetzt
- [ ] Anzahl Flaggen falsch gesetzt
- [ ] Timer

**Comment by Jules-sh** [comment]
Datei auf dem Dateisystem, welches die bisherigen Statistiken anzeigt
