### ISSUE TITLE
Spieler bewegen

### ISSUE THREAD

**Issue by Jules-sh** [NickRTR-Schule/Gehweg-Parcours#3]
Backlog Item:
Als Spieler möchte ich mit der linken Maustaste eine Gehwegplatte betreten, um zu zeigen, dass sich dort kein Hundehaufen befindet.

Tätigkeiten:
- Mouse Listener
- Spielermarkierung in Array

**Comment by NickRTR** [comment]
Bewege Spieler Methoden unnötig?
