### ISSUE TITLE
Platte mit Hundehaufen

### ISSUE THREAD

**Issue by Jules-sh** [NickRTR-Schule/Gehweg-Parcours#4]
Backlog Item:
Als Spieler möchte ich nach dem Betreten einer Gehwegplatte mit Hundehaufen sehen, dass ich das Spiel verloren habe, um nicht einfach weiterzuspielen

Tätigkeiten:
- Prüfung mit if bei Betreten einer Platte
- Fehlermeldung ausgeben
- Spiel beenden

**Comment by NickRTR** [comment]
Abgeschlossen!
