### ISSUE TITLE
Hundehaufenanzahl um aktuelle Platte

### ISSUE THREAD

**Issue by Jules-sh** [NickRTR-Schule/Gehweg-Parcours#5]
Backlog Item:
Als Spieler möchte ich nach dem Betreten einer Gehwegplattte ohne Hundehaufen sehen, wie viele Hundehaufen sich direkt um diese Gehwegplatte herum befinden, um meine nächsten Schritte gezielt zu setzen

Tätigkeiten:
- Prüfung umliegender Platten durch for Schleife
- zahl der umliegenden Hundehaufen sammeln und ausgeben

**Comment by NickRTR** [comment]
Nach Debugging: Die übergebene Spalte und Zeile des Spielfelds ist willkürlich und passt nicht zur geklickten Platte.

**Comment by Jules-sh** [comment]
Hinzugefügt mit c1eddfb3d9f10e949a22680fd57f0afa94bedb17

Issue closed
