### ISSUE TITLE
Spiel gewinnen

### ISSUE THREAD

**Issue by Jules-sh** [NickRTR-Schule/Gehweg-Parcours#7]
Backlog Item:
Als Spieler möchte ich nach der richtigen Vermutung aller Hundehaufen sehen, dass ich gewonnen habe, um mich zu freuen und zu sehen, dass das Spiel beendet ist.

Tätigkeiten:
- Prüfung mit if bei Setzung einer Vermutung
- Wenn alle richtig vermutet wurden, ausgeben einer Siegesmeldung

**Comment by NickRTR** [comment]
Reviewed 👍
