### ISSUE TITLE
Zurücknehmen einer Vermutung

### ISSUE THREAD

**Issue by Jules-sh** [NickRTR-Schule/Gehweg-Parcours#8]
Backlog Item:
Als Spieler möchte ich die Vermutung eines Hundehaufens auf einer Gehwegplatte zurücknehmen, um woanders Hundehaufen zu vermuten.

Tätigkeiten:
- Anzahl Vermutungen - 1
- Platte freigeben
- Mögliche Vermutungen + 1

**Comment by NickRTR** [comment]
Funktioniert mit Rechtsklick 👍
